### ISSUE TITLE
Shows empty popup on first installation

### ISSUE THREAD

**Issue by rugk** [SecUSo/PassSec-plus#8] opened 2016-07-22 10:12 UTC
After installing the add-on and restarting Firefox it shows me a message that PassSecPlus can be configured (which is also a quite useless message IMHO) and then it shows this:

![passecpopup](https://cloud.githubusercontent.com/assets/11966684/17054042/541963e2-5005-11e6-8997-93d220474924.png)

Firefox 47.0.1

**Comment by krisbr** [comment] 2016-07-24 07:55
Thanks for your report. I already noticed that a few people have issues when they're using Linux it's possible also related to the display resolution. 
I've cleaned up the code and tried to resolve this issue although I'm not able to reproduce it myself. Do you know how to temporarily deactivate the signature requirement in Firefox, so you could try the new update before I release it officially?
If you do please change the file extension of the [attached file](https://github.com/SecUSo/PassSec-plus/files/380178/PassSec-plus.zip) from "zip" to "xpi" and install it. I would be glad if you could report if it works for your.

**Comment by krisbr** [comment] 2016-07-28 21:29
I just released the new version where the bug should be fixed. If you still experience some problems please comment again.

**Closed by krisbr** 2016-07-28 21:29 UTC
Labels: bug
